### ISSUE TITLE
Several errors with different pdf files

### ISSUE THREAD

**Issue by MaxDaten** [Yuras/pdf-toolbox#28]
Hi and it's me again,

sorry for probably getting on your nerves. I have several `PdfDocumentError` errors with pdf files I can only send you via e-mail again. But these seem to be related. Here an excerpt:

- `PdfDocumentError (AnnotatedError "reading stream content: Stream (Dict [(Name \"Ty..." (AnnotatedError "Can't decode stream" (UnexpectedError "Filter not found: Name \"CCITTFaxDecode\"")))` 
- `PdfDocumentError (AnnotatedError "reading stream content: Stream (Dict [(Name \"Bi..." (AnnotatedError "Can't decode stream" (UnexpectedError "Filter not found: Name \"CCITTFaxDecode\"")))`
- `PdfDocumentError (AnnotatedError "reading stream content: Stream (Dict [(Name \"Bi..." (AnnotatedError "Can't decode stream" (UnexpectedError "Filter not found: Name \"DCTDecode\"")))`

I can provide the pdf files with the according page number and error via email, if you are okay with it.

Greetings

**Comment by Yuras** [comment]
Hi,

The [runPdfWithHandle](http://haddock.stackage.org/nightly-2015-12-08/pdf-toolbox-document-0.0.7.0/Pdf-Toolbox-Document-Pdf.html#v:runPdfWithHandle) function takes a list of stream filters, and you probably are passing [knownFilters](http://haddock.stackage.org/nightly-2015-12-08/pdf-toolbox-core-0.0.4.0/src/Pdf.Toolbox.Core.Stream.html#knownFilters) list. Unfortunately it contains only "FlateDecode" stream filter (also see #1.)

You can implement necessary filters yourself, the API is pretty [simple](http://haddock.stackage.org/nightly-2015-12-08/pdf-toolbox-core-0.0.4.0/Pdf-Toolbox-Core-Stream-Filter-Type.html). See [pdf spec](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf) for documentation regarding the particular filter. E.g. section 3.3.5 (page 77) describes CCITTFaxDecode filter. I'll be happy to advice and I'll accept pull requests :)

If you are not able to implement the filters yourself, then please let me know. I'll try to find time to do implement them.

**Comment by Yuras** [comment]
BTW, are you really interested in a filtered stream content? In case you just want to copy data into other PDF file, you can use just a raw stream content, see [rawStreamContent](http://haddock.stackage.org/nightly-2015-12-08/pdf-toolbox-core-0.0.4.0/Pdf-Toolbox-Core-Stream.html#v:rawStreamContent) function.

**Comment by MaxDaten** [comment]
Okay thanks for your quick response, I will take the evening and try it out :) I will keep you updated.

**Comment by Yuras** [comment]
So you got the errors while extracting text? Then it is probably a bug, CCITTFaxDecode and DCTDecode usually are used for images, not for text. Please send me the file, I'll take a look. See the email in my profile.

**Comment by MaxDaten** [comment]
Mail is out (sent from maxdaten@gmail). Maybe I'm provoking the bug somehow? I will have a look after lunch.

**Comment by MaxDaten** [comment]
Propally not the most elegant program but wrote a small demonstration how I use your library.
https://gist.github.com/MaxDaten/f22ad7d3751e2aea2e50

I wrote small `Conduit` wrappers to stream pages of text with page numbers. The program takes a directory as an argument and scans for pdf files. Then it just prints the page numbers until an exception occurs. Did I use some functions that in conflict with the default stream filters for text?

Call me lazy (thats why I'm using haskell, ha!), but I don't want to implement the StreamFilters, unless they are needed for normal text processing :)

**Comment by Yuras** [comment]
It is a bug introduced when implementing xobject support, #27. We should handle only Form xobjects when extracting text and ignore everything else. Incidentally it seems to be [done right](https://github.com/Yuras/pdf-toolbox/commit/60de9802c7b2f6c41f44948eaeaba945e93956c5#diff-9a14a0aed860153fbf75ec8d6fbdfe9bR157) in master.

I fixed it is xobject-form branch, will merge shortly.

Thank you for reporting the issue.

**Comment by MaxDaten** [comment]
Thank you for your work. I owe you, again :)

**Comment by MaxDaten** [comment]
Just want do add: I can confirm, the filter errors are gone, thats great :) But unfortunately I'm still getting:

```
PdfDocumentError (UnexpectedError "UnresolvedEntityException (fromList [\"nbsp\"])")
```

I will investigate it further, to narrow down the corresponding documents and pages.

**Comment by Yuras** [comment]
Fixed in stable via 271b9797a74fe6481b436a2bbc06a8ca00e0d25d.

Please open a separate issue for "UnresolvedEntityException" if it is reproducible.

**Comment by MaxDaten** [comment]
Thank you again and sorry I messed my error reporting up. I guess I'm a bit over-worked this week. The `UnresolvedEntityException` was falsely reported as an PDF error of my indexer but was in fact an error in the epub.  Sorry for the false alarm :(
